apiVersion: v1
kind: Namespace
metadata:
  name: store
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-volume-mssql-claim
  namespace: store
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mssql-deployment
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-mssql
  template:
    metadata:
      labels:
        app: product-mssql
    spec:
      containers:
        - name: product-mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: product-volume-mssql
      volumes:
        - name: product-volume-mssql
          persistentVolumeClaim:
            claimName: product-volume-mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: product-mssql-clusterip-service
  namespace: store
spec:
  type: ClusterIP
  selector:
    app: product-mssql
  ports:
    - name: product-mssql
      protocol: TCP
      port: 1001
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: product-mssql-loadbalancer
  namespace: store
spec:
  type: LoadBalancer
  selector:
    app: product-mssql
  ports:
    - name: product-mssql
      protocol: TCP
      port: 1001
      targetPort: 1433
