apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: storeves-pj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-server
  template:
    metadata:
      labels: 
        app: rabbitmq-server
    spec:
      containers:
        - name: rabbitmq-server
          image: rabbitmq:3-management
          ports:
            - containerPort: 15672
              name: rbmq-mng-port
            - containerPort: 5672
              name: rbmq-msg-port
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip-srv
  namespace: storeves-pj
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-server
  ports:
    - name: rbmq-mng-port
      protocol: TCP
      port: 1200
      targetPort: 15672
    - name: rbmq-msg-port
      protocol: TCP
      port: 1201
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
  namespace: storeves-pj
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq-server
  ports:
    - name: rbmq-mng-port
      protocol: TCP
      port: 1200
      targetPort: 15672
    - name: rbmq-msg-port
      protocol: TCP
      port: 1201
      targetPort: 5672
