apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-volume-mssql-claim
  namespace: storeves-pj
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi